services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "n8n"
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "SairohithTappatla"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Sairohith@005"
      - key: N8N_PORT
        value: 10000
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: WEBHOOK_URL
        value: "https://n8n-deploy-853e.onrender.com"
      - key: VUE_APP_URL_BASE_API
        value: "https://n8n-deploy-853e.onrender.com"
